// app
export const SET_CURRENT_APP_PAGE = 'SET_CURRENT_APP_PAGE';

// player list
export const SET_DISCOVERING_PLAYERS = 'SET_DISCOVERING_PLAYERS';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
export const SET_NUMBER_OF_PLAYERS_PER_PAGE = 'SET_NUMBER_OF_PLAYERS_PER_PAGE';
export const SET_PLAYERS_ON_THIS_PAGE = 'SET_PLAYERS_ON_THIS_PAGE';
export const ADD_CHUNK_OF_PLAYERS = 'ADD_CHUNK_OF_PLAYERS';
export const SET_PLAYER_DETAILS = 'SET_PLAYER_DETAILS';
export const DISCOVER_PLAYER_DETAILS = 'DISCOVER_PLAYER_DETAILS';

// player details pop
export const SET_PLAYER_DETAILS_LOADING = 'SET_PLAYER_DETAILS_LOADING';
export const SET_PLAYER_DETAILS_PLAYER = 'SET_PLAYER_DETAILS_PLAYER';
