export const SET_DISCOVERING_PLAYERS = 'SET_DISCOVERING_PLAYERS';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
export const SET_NUMBER_OF_PLAYERS_PER_PAGE = 'SET_NUMBER_OF_PLAYERS_PER_PAGE';
export const SET_PLAYERS_ON_THIS_PAGE = 'SET_PLAYERS_ON_THIS_PAGE';
export const ADD_CHUNK_OF_PLAYERS = 'ADD_CHUNK_OF_PLAYERS';
